# This workflow build the Allfeat node in release mode for each architecture and upload the binaries as artifacts.
name: Build And Publish Node

permissions:
  id-token: write
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-22.04
            out_name: allfeat-linux-x86_64
          - arch: aarch64
            runner: ubuntu-22.04-arm
            out_name: allfeat-linux-aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libclang-dev

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          cargo build --release --locked --verbose

      - name: Prepare artifacts
        run: |
          mkdir dist
          cp target/release/allfeat dist/${{ matrix.out_name }}

      - name: Upload artifacts to S3
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.OVH_S3_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OVH_S3_SECRET }}
          OVH_S3_ENDPOINT:       https://s3.eu-west-par.io.cloud.ovh.net
          BUCKET:                allfeat-prod-binaries-releases
          BRANCH:                ${{ github.ref_name }}
          FILE:                  ${{ matrix.out_name }}
        run: |
          echo "Uploading $FILE to s3://$BUCKET/$BRANCH/$FILE"
          aws --endpoint-url "$OVH_S3_ENDPOINT" s3 cp "dist/$FILE" "s3://$BUCKET/$BRANCH/$FILE" --acl public-read --only-show-errors

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out_name }}
          path: |
            dist/${{ matrix.out_name }}

