# This workflow build the Allfeat node in release mode for each architecture and upload the binaries as artifacts.
name: Build And Publish Node

permissions:
  id-token: write
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-22.04
            out_name: allfeat-linux-x86_64
          - arch: aarch64
            runner: ubuntu-22.04-arm
            out_name: allfeat-linux-aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          cargo build --release --locked --verbose

      - name: Prepare artifacts
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/allfeat dist/${{ matrix.out_name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::679799252113:role/AllfeatCiArtifactUploader
          aws-region: eu-west-3

      - name: Upload artifacts to S3
        run: |
          BUCKET="allfeat-prod-binaries-releases"
          BRANCH="${{ github.ref_name }}"
          FILE="${{ matrix.out_name }}"

          echo "Uploading $FILE to s3://$BUCKET/$BRANCH/$FILE"

          aws s3 cp "dist/$FILE" "s3://$BUCKET/$BRANCH/$FILE"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out_name }}
          path: |
            dist/${{ matrix.out_name }}


